name: Image Publisher

on:
  release:
    types: [ published ]

jobs:
  setup-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the image
        run: |
          docker buildx create --name mainbuilder --driver docker-container --platform linux/amd64 --use
          
          docker buildx build --push \
            --build-arg VERSION=${{ github.event.release.tag_name }} \
            --provenance=false \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/onthespot-docker:${{ github.event.release.tag_name }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/onthespot-docker:latest \
            .
